name: Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.22]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build the binary
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o smeditor
          else
            GOOS=darwin GOARCH=amd64 go build -o smeditor
          fi

      - name: Create release assets
        id: create-release
        run: |
          mkdir -p release
          mv smeditor release/

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: smeditor-${{ matrix.os }}-${{ matrix.go-version }}
          path: release/

