name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  GO_VERSIONS: 1.22
  OS_LIST: ubuntu-latest, macos-latest


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ ${{ env.GO_VERSIONS }} ]
        os: [ ${{ env.OS_LIST }} ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build the binary
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o smeditor
          else
            GOOS=darwin GOARCH=amd64 go build -o smeditor
          fi

      - name: Create release assets
        id: create-release
        run: |
          mkdir -p release
          mv smeditor release/

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: smeditor-${{ matrix.os }}-${{ matrix.go-version }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ $GO_VERSIONS ]
        os: [ $OS_LIST ]

    steps:
      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          path: release/smeditor-${{ matrix.os }}-${{ matrix.go-version }}

      - name: Display structure of downloaded files
        run: ls -ln release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/smeditor-${{ matrix.os }}-${{ matrix.go-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
